# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import recognition_pb2 as recognition__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in recognition_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RecognitionStub(object):
    """Recognition 서비스 정의
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSession = channel.unary_unary(
                '/recognition.Recognition/CreateSession',
                request_serializer=recognition__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=recognition__pb2.CreateSessionResponse.FromString,
                _registered_method=True)
        self.StreamAudio = channel.stream_stream(
                '/recognition.Recognition/StreamAudio',
                request_serializer=recognition__pb2.StreamAudioRequest.SerializeToString,
                response_deserializer=recognition__pb2.StreamAudioResponse.FromString,
                _registered_method=True)
        self.GetSessionStatus = channel.unary_unary(
                '/recognition.Recognition/GetSessionStatus',
                request_serializer=recognition__pb2.GetSessionStatusRequest.SerializeToString,
                response_deserializer=recognition__pb2.GetSessionStatusResponse.FromString,
                _registered_method=True)
        self.CloseSession = channel.unary_unary(
                '/recognition.Recognition/CloseSession',
                request_serializer=recognition__pb2.CloseSessionRequest.SerializeToString,
                response_deserializer=recognition__pb2.CloseSessionResponse.FromString,
                _registered_method=True)


class RecognitionServicer(object):
    """Recognition 서비스 정의
    """

    def CreateSession(self, request, context):
        """새로운 인식 세션을 생성합니다.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamAudio(self, request_iterator, context):
        """평가를 위해 오디오 데이터를 스트리밍하고 인식 결과를 받습니다.
        양방향 스트리밍 RPC입니다.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSessionStatus(self, request, context):
        """세션의 상태를 가져옵니다.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseSession(self, request, context):
        """세션을 닫습니다.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecognitionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=recognition__pb2.CreateSessionRequest.FromString,
                    response_serializer=recognition__pb2.CreateSessionResponse.SerializeToString,
            ),
            'StreamAudio': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamAudio,
                    request_deserializer=recognition__pb2.StreamAudioRequest.FromString,
                    response_serializer=recognition__pb2.StreamAudioResponse.SerializeToString,
            ),
            'GetSessionStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSessionStatus,
                    request_deserializer=recognition__pb2.GetSessionStatusRequest.FromString,
                    response_serializer=recognition__pb2.GetSessionStatusResponse.SerializeToString,
            ),
            'CloseSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseSession,
                    request_deserializer=recognition__pb2.CloseSessionRequest.FromString,
                    response_serializer=recognition__pb2.CloseSessionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'recognition.Recognition', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('recognition.Recognition', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Recognition(object):
    """Recognition 서비스 정의
    """

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recognition.Recognition/CreateSession',
            recognition__pb2.CreateSessionRequest.SerializeToString,
            recognition__pb2.CreateSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamAudio(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/recognition.Recognition/StreamAudio',
            recognition__pb2.StreamAudioRequest.SerializeToString,
            recognition__pb2.StreamAudioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSessionStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recognition.Recognition/GetSessionStatus',
            recognition__pb2.GetSessionStatusRequest.SerializeToString,
            recognition__pb2.GetSessionStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recognition.Recognition/CloseSession',
            recognition__pb2.CloseSessionRequest.SerializeToString,
            recognition__pb2.CloseSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
